name: Python Unit Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Base backend deps
          pip install -r apps/backend/requirements.txt
          pip install pytest

      - name: Run unit tests
        env:
          # Ensure src is on the path, although pytest.ini in repo root sets this too
          PYTHONPATH: apps/backend/src
        run: |
          pytest -q apps/backend/tests/unit
